kouka_app/kouka2/urls.py
from django.urls import path

from . import views

app_name = 'kouka2'
urlpatterns = [
    path('',views.Kouka2View.as_view(),name='kouka2'),
]

kouka_app/kouka2_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('kouka2/', include('kouka2.urls')),
]

kouka_app/kouka2/models.py
from django.db import models

# Create your models here.

kouka_app/kouka2/forms.py
from django import forms

class Kouka2Form(forms.Form):
    name = forms.CharField(label='名前:', max_length=30)
    email = forms.EmailField(label='年齢:')
    title = forms.CharField(label='電話番号:', max_length=11)
    message = forms.CharField(label='Mail:')
    form = forms.CharField(label='住所:',max_length=100)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = '氏名を入力'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = '年齢を入力'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = '電話番号を入力'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メールアドレスを入力'

        self.fields['form'].widget.attrs['class'] = 'form-control col-13'
        self.fields['form'].widget.attrs['placeholder'] = '住所を入力'

kouka_app/kouka2/views.py
from django.views import generic

from .forms import Kouka2Form

class Kouka2View(generic.TemplateView,generic.FormView):
    template_name = "base.html"
    form_class = Kouka2Form

# Create your views here.

kouka_app/kouka2/templates/base.html
{% load static %}

<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
	<div id="wrapper">
        {% block header%}{% endblock %}
      {% for field in form %}
        <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                <strong>{{ field.label_tag }}</strong>
            </label>
            <div class="col-sm-8">
                {{field}}
                {{field.errors}}
            </div>
        </div>
      {% endfor %}
    
    <div class="offset-sm-4 col-sm-8">
      <button class="btn btn-primary" type="submit">送信</button>
    </div>
        {% if messages %}
          <div class="container">
              <div class="row">
                  <div class="my-div-style w-100">
                    <a class="navbar-brand" href="{% url 'kouka2:kouka2' %}"></a>
                      <ul class="messages" style="list-style: none;">
                          {% for message in messages %}
                          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                              {{ message }}
                          </li>
                          {% endfor %}
                      </ul>
                  </div>
              </div>
          </div>
        {% endif %}

        {% block contents%}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
          <div class="container">
            <p class="m-0 text-center text-white small">Copyright &copy; Private Dairy 2019</p>
          </div>
          <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  	</div>
  </body>

</html>

kouka_app/kouka2/templates/kouka1.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | Private Diary{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}